config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status, optional: true
  has_many :order_items
  before_create :set_order_status
  has_many :products
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
belongs_to :product, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :order, optional: true
 has_many :order_items
 mount_uploader :image, ImageUploader
  default_scope { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end


end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
  	
    def index
        @orders = Order.all
        
    end
    def show
    	@order = Order.find(params[:id])
    	
    end
    def new
        @order = Order.new
    end
    def create
       @order = Order.new(order_params)
       if @order.save
      	   redirect_to @order
       else 
      	   render 'new'
      end
    end
    def destroy
      @order =Order.find(params[:id])
        @order.destroy
         redirect_to orders_path
    end

    private
      def order_params
             params.require(:order).permit(:subtotal, :tax, :shipping, :total)
     end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
def show
	@product = Product.find(params[:id])
	@order_item = current_order.order_items.new
end
def new
    @product = Product.new
end
def create
   @product = Product.new(product_params)
    if @product.save
        	   redirect_to @product
         else 
        	   render 'new'
          end
      end
      private
      def product_params
         params.require(:product).permit(:image, :name, :price, :discription, :order_id)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
  <h1>
    There are no items in your shopping cart.Please <%= link_to "go back", root_path %> and add some items to your cart.</h1>
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<h1>My Cart</h1>
<div class="shopping-cart">
  <%= render "shopping_cart" %>
  <%= link_to "Shopping Continue", products_path, class: "btn btn-link", class: "btn btn-danger" %>
  
  
  <%= link_to "Place Order", orders_path(order: current_order), class: "btn btn-link", :method => "get", class: "btn btn-primary" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link", class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
     <style>
       
        
        .background-color{
          color: black;
        }
    
    </style>
  </head>
  

  <body>
  <header>
     <nav class="navbar navbar " style="background-color: #06305f;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Shopping App</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><h1><%= link_to "My Store", root_path %></h1></li>
      <li><%= link_to "#{current_order.order_items.size} My Cart", cart_path %></li>
      <li><%= link_to "New Product", new_product_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right" >
     <% if user_signed_in? %> 
       <listyle style="color: black;">Logged in as <strong><%= current_user.email %></strong></li>
                 <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> <span class="glyphicon glyphicon-user"></span> </li>|
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %><span class="glyphicon glyphicon-log-out"></span> </li>
            <% else %>
       
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %><span class="glyphicon glyphicon-user"></span> </li>|
                <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %><span class="glyphicon glyphicon-log-in"></span></li>
            <% end %>
    </ul>
  </div>
</nav> 
</header>

  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>
    <footer></footer>
    </div>
  </body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/orders/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
      <%= image_tag product.image.url %>
    </div>
    <div class="col-xs-4">
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order.total_price %></span></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/_shopping_cart.html.erb
 <% orders.each do |order| %>
    <%= render 'carts/cart_row', product: order.product, order: order, show_total: true %>
 
<% end %>

app/views/orders/index.html.erb
<h1> Order Summary</h1>
<tr>
<strong>Login With Email:</strong>
<td><%= current_user.email %></td>
<td>
 <%= link_to "Change", new_user_session_path, :class => 'navbar-link', class: "btn btn-primary"  %>
 
 </td>
 </tr><br>
 <%#= render "shopping_cart", orders: @orders %>
<% @orders.each do |order| %>
<% order.order_items.each do |item|%>
	 			<tr>
	 				<td><%= item.product.name%></td>
	 				<td><%= item.unit_price%></td>
	 				<td><%= item.quantity%></td>
	 				<td><%= item.total_price%></td>
	 				<td><%= image_tag(item.product.image.url)%></td>
	 				    <%= link_to "remove", order_path(order),
              method: :delete,
              data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>

	 			</tr>
<% end %>
<% end %>

app/views/orders/show.html.erb
<h1>Payment Options</h1>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
       <strong>Name:</strong></br>
         <h4><%= product.name %></small></h4>
      <strong>Item:</strong></br>
        <h4><%= product.item %></h4>
      <strong>Discription:</strong></br>
        <h4><%= product.discription %></h4>
      <strong>Price:</strong></br>
        <h4><%= number_to_currency product.price %></h4>
   
    <div class="col-xs-4">
      <div class="size">
        <%= image_tag product.image.url, width: "400%" %>
        
      </div>
       </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1 class="text-center">Products For Sale</h1>
<div class = "column">
    <% @products.each do |product| %>
     <div class = "col-md-6">
      <div class="thumbnail">
        <h4><a href="/products/<%= product.id %>"><%= render "product_row", product: product, order_item: @order_item %></a></h4>
      </div>
      </div>
    <% end %>
    </div>
  

app/views/products/new.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
<p><%= f.label :image, "Upload Images:" %>
  <%= f.file_field :image %>
  </p>
  <p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </p>
   <p>
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </p>
  <p>
    <%= f.label :price%><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :Discription %><br>
    <%= f.text_area :discription %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/products/show.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <strong>Name:</strong></br>
      <h4><%= @product.name %></small></h4>
        <strong>Item:</strong></br>
      <h4><%= @product.item %></h4>
        <strong>Discription:</strong></br>
      <h4><%= @product.discription %></h4>
        <strong>Price:</strong></br>
      <h4><%= number_to_currency @product.price %></h4>
    </div>
    <div class="col-xs-4">
    <p><%= image_tag @product.image.url %></p>
    <%= form_for @order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency @product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 0, class: "form-control", min: 0 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
          <div class="input-group-btn">
            <%= link_to "Buy Now", orders_path, class: "btn btn-link", class: "btn btn-danger"%>
             
          </div>
        </div>
      <% end %>
      </div>
    
  </div>
</div>